x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "5"

services:
  goj-mysql:
    image: mysql:8.0
    container_name: goj-mysql
    restart: always
    security_opt:
      - seccomp:unconfined
    command:
      - --default-authentication-plugin=mysql_native_password
      - --max_connections=1024
      - --thread_cache_size=256
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --explicit_defaults_for_timestamp=true
      - --log_bin_trust_function_creators=1
    environment:
      - MYSQL_DATABASE=goj
      - MYSQL_USER=goj
      - MYSQL_PASSWORD=goj123456
      - MYSQL_ROOT_PASSWORD=root123456
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - goj-network
    logging: *default-logging

  goj-redis:
    image: redis:alpine
    container_name: goj-redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - goj-network
    logging: *default-logging

  goj-judge:
    image: krisliu16/goj-judge:latest
    container_name: goj-judge
    restart: always
    privileged: true
    shm_size: 512m
    ports:
      - "5050:5050"
    networks:
      - goj-network
    logging: *default-logging

  goj-backend:
    image: krisliu16/goj-backend:latest
    container_name: goj-backend
    restart: always
    environment:
      - DB_HOST=goj-mysql
      - DB_USER=goj
      - DB_PASSWORD=goj123456
      - DB_NAME=goj
      - REDIS_ADDR=goj-redis:6379
      - JUDGE_ADDR=http://goj-judge:5050
    ports:
      - "3000:3000"
    volumes:
      - ../goj-backend/data:/app/data
    depends_on:
      - goj-mysql
      - goj-redis
    networks:
      - goj-network
    logging: *default-logging

  goj-frontend:
    image: krisliu16/goj-frontend:latest
    container_name: goj-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - goj-backend
    networks:
      - goj-network
    logging: *default-logging

networks:
  goj-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
  problem_data: